### ISSUE TITLE
Standard alternative extension for stub files

### ISSUE THREAD

**Issue by JukkaL** [JukkaL/typing#10]
Maybe define `.pyi` (or something else) as a standard extension for stub files. If we don't have a standard extension, different tools could use different extensions.

**Comment by JukkaL** [comment]
`.pyi` is now supported by mypy as an alternative for `.py`. All the bundled stubs still use the `.py` extension, though.

**Comment by gvanrossum** [comment]
TBH I don't think the use case is very strong.

**Comment by JukkaL** [comment]
This issue gives potential use cases for the alternative extension: https://github.com/JukkaL/mypy/issues/345

We could also store stubs in standardized locations (e.g., any .py file under a `stubs` directory would be considered a stub, see https://github.com/ambv/typehinting/issues/22).

If stubs follow different rules from normal files, such as if they support multiple signatures / overloading (while normal modules don't), we need a way of distinguishing between a stub file and a normal source file.

**Comment by gvanrossum** [comment]
OK, it's no big deal, let's support `.pyi`.

**Comment by JukkaL** [comment]
`.pyi` is now supported by mypy.
