### ISSUE TITLE
Change license to Apache License 2.0

### ISSUE THREAD

**Issue by JukkaL** [JukkaL/typing#15]
This is needed for contributing code to PSF.

**Comment by akaihola** [comment]
Also, currently the repository contains confusing license files. `LICENSE` in the repository root contains the PSF license, while `python2/LICENSE` contains both the mypy MIT license and the PSF license. The Mypy license also contains this note:
>Portions of mypy are licensed under different licenses.  The files
>under lib-python and lib-typing/3.2 are licensed under the PSF 2
>License, reproduced below.

**Comment by gvanrossum** [comment]
Won't fix here.
