### ISSUE TITLE
Decide what to do if library class name is private / has funny name

### ISSUE THREAD

**Issue by JukkaL** [JukkaL/typing#18]
Some library types are not nicely exposed by the public interface. For example, `re.compile` returns an instance of `_sre.SRE_Pattern`, but this seems like an implementation detail and it's not obvious how to refer to this type:

```
>>> import re
>>> re.compile('XY')
<_sre.SRE_Pattern object at 0x7fee9c7b2490>
>>> import _sre
>>> _sre.SRE_Pattern
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'SRE_Pattern'
```

We need a documented way of dealing with cases like this. 

This is related to #17 -- some of the suggestions there might work here.

**Comment by gvanrossum** [comment]
In cases where we can't fix it (e.g. when describing stubs for an older Python version) I propose that we add the desired type to the stub for the relevant module (e.g. re) with a more reasonable name that starts with an underscore. (Hopefully that's not a problem.)

**Comment by JukkaL** [comment]
Just adding the type to a stub is not optimal, since references to the type should be valid expressions so that they can be used in function annotations. Having to use string escaping for these types would be awkward and look ugly.

After thinking about this more since I wrote #17, it seems that having separate modules that just define aliases for the types (for backward compatibility) might be an acceptable approach. For example, we could have a `re_types` module that contains type aliases for `re`. The stub would just import the types:

```python
# re_types stub
from re import Pattern, Match
```

The implementation would define the types:

```python
# re_types implementation
import re
import typing

Pattern = typing.TypeAlias(type(re.compile('')))
Match = typing.TypeAlias(type(re.match('', '')))
# We need TypeAlias for generic types only; otherwise we can use just Name = type(expr)
```

Now we can use the types in code that needs to be compatible with both new Python versions (which would hopefully define `re.Pattern`) and old Python versions (which don't define `re.Pattern`):

```
import re
from re_types import Pattern

def c(x: str) -> Pattern[str]:
    return re.compile(x)
```

An important bit is that we need a naming convention for the type alias modules (e.g., `re` -> `re_types`), but only for consistency. 

We also need some way of distributing these alias modules (both the implementations and the stubs). For standard library modules, we could have a pypi package that installs aliases for all (supported) standard library modules. Alternatively, they could be included in the package for typing. Most modules don't need an alias module, since they don't define any generic classes and they don't have private type objects or types with funny names.

**Comment by gvanrossum** [comment]
I like having a separate module re_types.py and I like the naming convention <name>_types.py.

- How does ``from re import Pattern, Match`` in the stub help the type checker, and how does it know that these are generic over AnyStr (if they are)?
- I'd like the runtime Pattern and Match classes to be introspectable so you can discover that they are generic over AnyStr, and I'd like them to respond reasonably to issubclass() and isinstance().

For the stdlib modules the distribution (needed for Python 3.4 and older) could be bundled with typing.py.

Hm, maybe distribution would be simpler if these modules were submodules of typing (which would then technically become a package, with default export of the things we've discussed so far). Then maybe the name should be "typing.re" so application code can write "from typing.re import Pattern, Match"?

**Comment by JukkaL** [comment]
I like the idea of `typing.re`, expect for the fact that I don't know how to deal with packaging. It should be possible to have different submodules of `typing` under different parent directories, and I'm not sure how this would work in a way that would avoid conflicts between different versions of `typing`.

For example, assume that `sys.path` has entries `/foo` and `/bar`. These have different submodules:

```
/foo/typing/re.py
/bar/typing/acme.py
```

Would both of them need a separate `typing/__init__.py`? But if `typing` is included in the standard library, a third-party typing submodule shouldn't override the default standard library module. There could be a simple way around this, but I'm not familiar enough with packaging to know it. Or maybe third-party type modules would have to live outside `typing`?

**Comment by ambv** [comment]
AFAICT all solutions for namespace packages disallow actual contents in them:
1. `pkgutil.extend_path` and `pkg_resources.declare_namespace` require the same __init__.py in all places so that the import order doesn't matter
2. PEP 420 states that __init__.py must not be present for a package to be considered namespace

That being said, a shared package tree to put stubs in would be great.
```pip install typing-MySQL-python```

**Comment by gvanrossum** [comment]
I forgot that distinction of namespace packages. :-( But do we really need a namespace package if this is just for stdlib modules? For 3rd party modules we could adopt a different naming scheme, but for the stdlib I don't see a reason to want to merge multiple distribution packages (even if it's Python 3.4 or lower).
