### ISSUE TITLE
Switch the argument order of cast

### ISSUE THREAD

**Issue by JukkaL** [JukkaL/typing#19]
Currently casts work like this:
    
    x = cast(int, y)

However, this could be considered inconsistent, since in annotations the type comes after the variable. Maybe reverse the order of arguments:

    x = cast(y, int)

However, it can also be argued that the default value for a function argument comes after the type, so this is actually already consistent, kind of:

    def f(x: int = y) -> ...: ...

Any opinions?

**Comment by gvanrossum** [comment]
IIRC cast's origins are in C/C++, where the type always comes first. This feels pretty minor and I think cast(type, int) is fine.

Cross-reference: https://github.com/ambv/typehinting/issues/15

**Comment by kirbyfan64** [comment]
Honestly...I always kind of wanted the ability to do this:

```python
cast[type](x)
```

It seems more straightforward, especially when you consider C++'s cast functions (mostly reinterpret_cast).

**Comment by gvanrossum** [comment]
However, ``cast[type](x)`` looks more magical. I think we should try to stick to the (loose) rule that the ``z = x[y]`` notation means that generic or pseudo type x is parameterized with type y giving another type z. But here the result of calling ``cast[type]`` isn't really a type -- it is a function that returns its argument unchanged but tells the static analyzer something about its type. 

Or do you have a good use case for ``cast[type]`` (i.e. not calling it immediately)? That might change my opinion. (Assuming the static checker can be made smart enough to track assignments of ``cast[type]``, at least to simple local or global variables.)

**Comment by JukkaL** [comment]
The type of `cast[t]` would be `Callable[[Any], t]`. A static checker could treat it as a special kind of an expression, and type inference would work just fine. I don't see a common use case for using `cast[type]` without calling it immediately, though.

**Comment by gvanrossum** [comment]
Then I think one pair of brackets plus a comma is better than two pairs of
brackets. We're not following Haskell here... :-)

On Tuesday, January 6, 2015, Jukka Lehtosalo <notifications@github.com>
wrote:

> The type of cast[t] would be Callable[[Any], t]. A static checker could
> treat it as a special kind of an expression, and type inference would work
> just fine. I don't see a common use case for using cast[type] without
> calling it immediately, though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JukkaL/typing/issues/19#issuecomment-68984110>.
>


-- 
--Guido van Rossum (on iPad)

**Comment by JukkaL** [comment]
Closing this, as the original syntax is the one preferred by PEP 484 (https://github.com/ambv/typehinting/issues/15).
