### ISSUE TITLE
Maybe make overload not depend on sys._getframe

### ISSUE THREAD

**Issue by JukkaL** [JukkaL/typing#20]
Currently `@overload` uses `sys._getframe`, which is potentially bad. Consider using a variant API that doesn't need it, such as this (somebody suggested this a long time ago, this is not my idea):

```
@overloaded
def f(x: int) -> int: return 1

@f.overload
def f(x: str) -> str: return 'x'
```

Of course, in real code the name `f` would be longer and this would look somewhat less nice. However, overloading is not needed very often now that we have typevars with values and union types, so this seems like a very minor issue.

**Comment by gvanrossum** [comment]
Cross-reference: https://github.com/ambv/typehinting/issues/14

**Comment by JukkaL** [comment]
Overloads are now only supported in stubs. Closing this.
