### ISSUE TITLE
Don't expose AbstractGeneric, AbstractGenericMeta and GenericMeta via public API

### ISSUE THREAD

**Issue by vlasovskikh** [JukkaL/typing#36]
Are these classes necessary and useful as a part of the public API of typing?

* `AbstractGeneric`
* `AbstractGenericMeta`
* `GenericMeta`

I don't see useful scenarios for them in the user code, since in my opinion `Generic` would be enough.

**Comment by JukkaL** [comment]
Further discussion should happen here: https://github.com/ambv/typehinting/issues/41.
