### ISSUE TITLE
Decide what to do with Protocol

### ISSUE THREAD

**Issue by JukkaL** [JukkaL/typing#4]
The implementation contains `Protocol` which is intended to support structural subtyping. Decide whether this will be part of the official API and document it if will be.

**Comment by gvanrossum** [comment]
Cross-reference: https://github.com/ambv/typehinting/issues/11

**Comment by JukkaL** [comment]
Protocols will be left out of PEP 484, so I'll remove it from `typing`.

**Comment by JukkaL** [comment]
Actually just renamed `Protocol` to `_Protocol`, since it's arguably still useful within the implementation. We can reconsider this later.
