### ISSUE TITLE
On Python 2.7, `python setup.py install` installs the Python 3 version

### ISSUE THREAD

**Issue by akaihola** [JukkaL/typing#45]
Even though `setup.py` uses `python2/` as `package_dir` when running on Python 2.7, `python setup.py install` still installs the Python 3 `typing.py` found in the repository root.

Strangely, if I delete `typing.py` from the repository root before running `python setup.py install`, it *does* install the correct version from `python2/typing.py`.

**Comment by akaihola** [comment]
A simple solution is to move `typing.py` and `test_typing.py` from the repository root into a new `python3/` subdirectory, and make this change in `setup.py`:
```diff
diff --git a/setup.py b/setup.py
index c1f7183..df2849f 100644
--- a/setup.py
+++ b/setup.py
@@ -28 +28 @@ tools.
-package_dir = {2: 'python2', 3: '.'}[sys.version_info.major]
+package_dir = {2: 'python2', 3: 'python3'}[sys.version_info.major]
```

**Comment by JukkaL** [comment]
Thanks for reporting this! This needs to be fixed soon.

**Comment by gvanrossum** [comment]
The installer from https://github.com/ambv/typehinting works for Python 2.
