### ISSUE TITLE
Add generic alias for namedtuple

### ISSUE THREAD

**Issue by JukkaL** [JukkaL/typing#7]
We should probably have something like `List[T]` for namedtuple.

**Comment by gvanrossum** [comment]
Cross-reference: https://github.com/ambv/typehinting/issues/21

**Comment by JukkaL** [comment]
Mypy now supports `NamedTuple('X', [('item', type), ...])`: https://github.com/JukkaL/mypy/issues/460

**Comment by JukkaL** [comment]
Added the implementation from mypy.
